### ISSUE TITLE
Missed package @jjppof/chartjs-plugin-zoom-pan-select under npm

### ISSUE THREAD

**Issue by storenth** [jjppof/chartjs-plugin-zoom-pan-select#1]
Did not found `jjppof` or `chartjs-plugin-zoom-pan-select` or `@jjppof/chartjs-plugin-zoom-pan-select` at https://www.npmjs.com/
Please, make sure you appropriately post the package.
Thank you.
<img width="1435" alt="Снимок экрана 2020-11-04 в 13 48 18" src="https://user-images.githubusercontent.com/18244131/98078333-774df680-1ea4-11eb-8349-ca7424777380.png">

**Comment by jjppof** [comment]
New publish done:
![image](https://user-images.githubusercontent.com/7890647/100370046-73654e00-2fe4-11eb-84f1-3ec1554934da.png)

**Comment by alvardsoler** [comment]
Hi, for now the package is missing in npm.
![imagen](https://user-images.githubusercontent.com/4102837/106158438-06a53600-6184-11eb-86f2-c8257c056f25.png)

**Comment by tomer-liran** [comment]
Hi, package is still missing. I tried installing it with the npm install command specified.
